### ISSUE TITLE
Link to local repository

### ISSUE THREAD

**Issue by thibaultdupont-cpe** [VCityTeam/TunNetView#2]
Why does this point outside the folder ?
https://github.com/VCityTeam/TunNetView/blob/67f5f984f0f959422acf8161ab2ec7e6160b0358/webpack.config.js#L19C26-L19C38

**Comment by EricBoix** [comment]
My bad. This version of the webpack configuration file is done for a development context where UD-Viz has to be patched for things to run (refer [here for more on this technique](https://github.com/VCityTeam/UD-Viz/blob/master/docs/static/Developers.md#develop-with-modified-ud-viz-library-in-your-demo)).
I fixed my erroneous commit with [this new commit](https://github.com/VCityTeam/TunNetView/commit/7abfc62fb7656d355bf96c4bb1253bf66d6d1181).
